In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option("display.max_columns", None)

In [8]:
df = pd.read_parquet("..\data\processed\data.parquet")

print(df.shape)
df.info()
df.sample(5)

(24043191, 18)
<class 'pandas.DataFrame'>
RangeIndex: 24043191 entries, 0 to 24043190
Data columns (total 18 columns):
 #   Column                   Dtype
---  ------                   -----
 0   observed_at              datetime64[us, UTC]
 1   stop_id                  str
 2   stop_name                str
 3   line_id                  str
 4   direction                str
 5   platform_name            str
 6   destination_name         str
 7   hour                     int32
 8   weekday                  int32
 9   is_weekend               int64
 10  time_to_station          int64
 11  roll_mean_tts_10m        float64
 12  roll_max_tts_10m         float64
 13  roll_count_10m           float64
 14  roll_std_tts_10m         object
 15  baseline_median_tts      float64
 16  deviation_from_baseline  float64
 17  late                     int64
dtypes: datetime64[us, UTC](1), float64(5), int32(2), int64(3), object(1), str(6)
memory usage: 5.5+ GB

,observed_at,stop_id,stop_name,line_id,direction,platform_name,destination_name,hour,weekday,is_weekend,time_to_station,roll_mean_tts_10m,roll_max_tts_10m,roll_count_10m,roll_std_tts_10m,baseline_median_tts,deviation_from_baseline,late
15094830,2026-03-03 08:30:43.922005+00:00,940GZZLUSTD,Stratford Underground Station,jubilee,unknown,Westbound - Platform 14,Stratford Underground Station,8,1,0,330,946.456218,1785.0,1359.0,None,939.0,-609.0,0
17398006,2026-02-25 10:15:13.492433+00:00,940GZZLUSWK,Southwark Underground Station,jubilee,inbound,Westbound - Platform 1,Stanmore Underground Station,10,2,0,187,480.628141,1133.0,199.0,None,567.0,-380.0,0
12580864,2026-03-03 13:10:08.975248+00:00,940GZZLUPCO,Pimlico Underground Station,victoria,inbound,Southbound - Platform 2,Brixton Underground Station,13,1,0,1291,817.714286,1496.0,371.0,None,821.0,470.0,1
1709189,2026-02-25 21:34:40.210924+00:00,940GZZLUBST,Baker Street Underground Station,jubilee,inbound,Northbound - Platform 10,Stanmore Underground Station,21,2,0,602,840.380309,1763.0,518.0,None,875.0,-273.0,0
4445585,2026-03-01 05:54:02.091680+00:00,940GZZLUCWR,Canada Water Underground Station,jubilee,outbound,Eastbound - Platform 2,Stratford Underground Station,5,6,1,1674,904.442748,1795.0,131.0,None,890.0,784.0,1

In [9]:
df.describe()

,hour,weekday,is_weekend,time_to_station,roll_mean_tts_10m,roll_max_tts_10m,roll_count_10m,baseline_median_tts,deviation_from_baseline,late
count,2.404319e+07,2.404319e+07,2.404319e+07,2.404319e+07,2.404319e+07,2.404319e+07,2.404319e+07,2.404319e+07,2.404319e+07,2.404319e+07
mean,1.357535e+01,2.923082e+00,2.674414e-01,7.442601e+02,7.470698e+02,1.497336e+03,4.623664e+02,7.367591e+02,7.500955e+00,2.756518e-01
std,5.891737e+00,1.919967e+00,4.426246e-01,4.960019e+02,2.205886e+02,4.313433e+02,3.245692e+02,2.177443e+02,4.495845e+02,4.468421e-01
min,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,-1.721000e+03,0.000000e+00
25%,9.000000e+00,1.000000e+00,0.000000e+00,3.120000e+02,6.335306e+02,1.251000e+03,2.760000e+02,6.280000e+02,-3.340000e+02,0.000000e+00
50%,1.400000e+01,3.000000e+00,0.000000e+00,6.840000e+02,8.203705e+02,1.728000e+03,3.820000e+02,8.050000e+02,0.000000e+00,0.000000e+00
75%,1.800000e+01,5.000000e+00,1.000000e+00,1.128000e+03,8.966459e+02,1.794000e+03,4.940000e+02,8.850000e+02,3.430000e+02,1.000000e+00
max,2.300000e+01,6.000000e+00,1.000000e+00,1.859000e+03,1.851000e+03,1.859000e+03,1.950000e+03,1.840000e+03,1.350000e+03,1.000000e+00

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24043191 entries, 0 to 24043190
Data columns (total 18 columns):
 #   Column                   Dtype
---  ------                   -----
 0   observed_at              datetime64[us, UTC]
 1   stop_id                  str
 2   stop_name                str
 3   line_id                  str
 4   direction                str
 5   platform_name            str
 6   destination_name         str
 7   hour                     int32
 8   weekday                  int32
 9   is_weekend               int64
 10  time_to_station          int64
 11  roll_mean_tts_10m        float64
 12  roll_max_tts_10m         float64
 13  roll_count_10m           float64
 14  roll_std_tts_10m         object
 15  baseline_median_tts      float64
 16  deviation_from_baseline  float64
 17  late                     int64
dtypes: datetime64[us, UTC](1), float64(5), int32(2), int64(3), object(1), str(6)
memory usage: 5.5+ GB